language: elixir
elixir:
  - '1.12.1'
otp_release:
  - '24.0.2'

jobs:
  include:
    - elixir: '1.12.1'
      otp_release: '24.0.2'

    - elixir: '1.11.4'
      otp_release: '23.3.4'

    - elixir: '1.10.4'
      otp_release: '23.3.4'

    - elixir: '1.9.4'
      otp_release: '22.2.8'
